Hypothesis:

1. State the Hypotheses statement:

In [ ]:
Hypothesis statement:

# Null Hypothesis (H0): The mean weekly operating cost is equal to the predicted cost based on the current model.
# ALternative Hypothis (H1): the mean weekly operating cost is greater than the predicted cost based on the current model.

# In mathematical terms:

# H0 : mu = $1000 + $5 * 600 = $4000
# H1 : mu > $4000

2. Calculate the Test Statistic:
Use the following formula to calculate the test statistic (t):
where:
ˉxˉ = sample mean weekly cost (Rs. 3,050)
μ = theoretical mean weekly cost according to the cost model (W = $1,000 + $5X for X = 600 units)
σ = 5*25 units
n = sample size (25 restaurants)

In [ ]:
import scipy.stats as stats
import numpy as np
import math

np.random.seed(10)
sample_size = 25
sample_mean = 3050
x_mean = 600
theoretical_mean = 1000 + 5 * x_mean
std_dev = 5 * sample_size

t_statistic = ((sample_mean - theoretical_mean)/(std_dev/math.sqrt(sample_size)))
print("t_statistic is:",t_statistic)

t_statistic is: -38.0


3. Determine the Critical Value:

Using the alpha level of 5% (α = 0.05), determine the critical value from the standard normal (Z) distribution table.

In [ ]:
t_critical = stats.t.ppf(q = 0.95,df=24)
print("t_critical value:" ,t_critical)

t_critical value: 1.7108820799094275


4. Make a Decision:

Compare the test statistic with the critical value to decide whether to reject the null hypothesis.

In [ ]:
if t_statistic > t_critical:
    print("Reject the null hypothesis")
    print("There is sufficient evidence to suggest that the mean weekly operating cost is greaterthan the predicted cost based on the current model.")
else:
    print("Fail to reject the null hypothesis")
    print("There is insufficient evidence to suggest that the mean weekly operating cost is greaterthan the predicted cost based on the current model.")



Fail to reject the null hypothesis
There is insufficient evidence to suggest that the mean weekly operating cost is greaterthan the predicted cost based on the current model.


5. Conclusion:
Based on the decision in step 4, conclude whether there is strong evidence to support the restaurant owners' claim that the weekly operating costs are higher than the model suggests.

Since the test statistic(t)=−38 is much less than the critical value , we do not reject the null hypothesis.
Based on the calculated test statistic, there is no strong evidence to support the restaurant owners' claim that the weekly operating costs are higher than the model suggests. In fact, the test statistic is highly negative, indicating that the observed sample mean is significantly lower than the theoretical mean according to the cost model. This result contradicts the owners' claim of higher costs.

##Chi-Square test

1. State the Hypotheses:

In [ ]:
Hypothesis Statement:

Null Hypothesis (H₀): There is no significant association between the type of device purchased (Smart Thermostats vs. Smart Lights) and customer satisfaction level.
                      In other words, the type of device and satisfaction level are independent.

Alternative Hypothesis (H₁): There is a significant association between the type of device purchased and customer satisfaction level.
                             In other words, the type of device and satisfaction level are not independent.

2. Compute the Chi-Square Statistic:

In [ ]:
import scipy.stats as stats
import numpy as np

observed = np.array([[50,70],[80,100],[60,90],[30,50],[20,50]])   #observed frequencies
Total_counts = np.array([120,180,150,80,70])                      #total counts
Total_devices = np.array([240,360])                               # total devices
Grand_total = np.sum(Total_counts)
Grand_total

600

In [ ]:
expected_frequencies = np.outer(Total_counts , Total_devices) / Grand_total   # calculate chi_square statistics
expected_frequencies

array([[ 48.,  72.],
       [ 72., 108.],
       [ 60.,  90.],
       [ 32.,  48.],
       [ 28.,  42.]])

In [ ]:
chi2_statistic,p_value,_,_= stats.chi2_contingency(observed,correction = False)   # compute chi_square statistics
chi2_statistic,p_value,_,_

(5.638227513227513,
 0.22784371130697179,
 array([[ 48.,  72.],
        [ 72., 108.],
        [ 60.,  90.],
        [ 32.,  48.],
        [ 28.,  42.]]),
 array([[ 48.,  72.],
        [ 72., 108.],
        [ 60.,  90.],
        [ 32.,  48.],
        [ 28.,  42.]]))

In [ ]:
stats.chi2_contingency(observed,correction = False)

Chi2ContingencyResult(statistic=5.638227513227513, pvalue=0.22784371130697179, dof=4, expected_freq=array([[ 48.,  72.],
       [ 72., 108.],
       [ 60.,  90.],
       [ 32.,  48.],
       [ 28.,  42.]]))

3. Determine the Critical Value:

In [ ]:
alpha = 0.05
df = (observed.shape[0]-1) * (observed.shape[1]-1)  # df = (no.of rows-1)*(no.of col-1)
critical_value = stats.chi2.ppf(1 - alpha,df)

In [ ]:
chi2_statistic, critical_value,df

(5.638227513227513, 9.487729036781154, 4)

4. Make a Decision:
Compare the Chi-Square statistic with the critical value to decide whether to reject the null hypothesis.

From the above calculations Chi-Square statistic is less than  critical value, so do not reject the null hypothesis,
implying no significant association between the type of device and customer satisfaction level.